services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    container_name: ${SERVICENAME}-db
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_INITDB_SKIP_TZINFO=1
    volumes:
      - "./docker/sql:/docker-entrypoint-initdb.d:ro"
      - "${VOLUMES_DIR}/mariadb:/var/lib/mysql"

  app:
    image: ghcr.io/mind-hochschul-netzwerk/${SERVICENAME}
    restart: unless-stopped
    container_name: ${SERVICENAME}
    environment:
      - WWW_ROOT=https://www.${DOMAINNAME}
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=database
      - SMTP_HOST
      - SMTP_SECURE
      - SMTP_AUTH_TYPE
      - SMTP_USER
      - SMTP_PASSWORD
      - IMAP_HOST
      - IMAP_SSL
      - IMAP_USER
      - IMAP_PASSWORD
      - LDAP_HOST=ldap://ldap:389/
      - LDAP_BIND_DN=cn=admin,dc=mind-hochschul-netzwerk,dc=de
      - LDAP_BIND_PASSWORD
    volumes:
      #- "./docker/moodledata-init.tar.bz2:/moodledata-init.tar.bz2:ro"
      - "${VOLUMES_DIR}/moodledata:/moodledata"
      - "./src/config.php:/var/www/html/config.php:ro"
      - "./src/akademieprogramm.php:/var/www/html/akademieprogramm.php:ro"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.${SERVICENAME}.entrypoints=websecure
      - traefik.http.routers.${SERVICENAME}.rule=Host(`www.${DOMAINNAME}`) || Host(`${SERVICENAME}.${DOMAINNAME}`) || Host(`${DOMAINNAME}`) || Host(`akademie.${DOMAINNAME}`) || Host(`mind-akademie.de`) || Host(`www.mind-akademie.de`)
      - com.centurylinklabs.watchtower.enable=false
    depends_on:
      - db
    networks:
      - default
      - traefik
      - ldap

  adminer:
    image: adminer:latest
    container_name: ${SERVICENAME}-adminer
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.${SERVICENAME}-adminer.entrypoints=websecure
      - traefik.http.routers.${SERVICENAME}-adminer.rule=Host(`${SERVICENAME}-adminer.${DOMAINNAME}`)
    networks:
      - default
      - traefik
    depends_on:
      - db

networks:
  traefik:
    name: traefik
    external: true
  ldap:
    name: ldap
    external: true
