version: "3.5"
services:
  moodle-database:
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD
    volumes:
      - "./docker/sql:/docker-entrypoint-initdb.d:ro"
      - "${VOLUMES_DIR}/mariadb:/var/lib/mysql"
    networks:
      - ${SERVICENAME}

  moodle:
    image: mindhochschulnetzwerk/${SERVICENAME}
    restart: unless-stopped
    environment:
      - WWW_ROOT=https://www.${DOMAINNAME}
      - DB_HOST=${SERVICENAME}-database
      - DB_USER=user
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=database
      - SMTP_HOST
      - SMTP_SECURE
      - SMTP_AUTH_TYPE
      - SMTP_USER
      - SMTP_PASSWORD
      - IMAP_HOST
      - IMAP_SSL
      - IMAP_USER
      - IMAP_PASSWORD
      - LDAP_HOST=ldap://ldap:389/
      - LDAP_BIND_DN=cn=admin,dc=mind-hochschul-netzwerk,dc=de
      - LDAP_BIND_PASSWORD
    volumes:
      - "./docker/moodledata-init.tar.bz2:/moodledata-init.tar.bz2:ro"
      - "${VOLUMES_DIR}/moodledata:/moodledata"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.${SERVICENAME}.entrypoints=websecure
      - traefik.http.routers.${SERVICENAME}.rule=Host(`www.${DOMAINNAME}`) || Host(`${SERVICENAME}.${DOMAINNAME}`) || Host(`${DOMAINNAME}`)
    depends_on:
      - ${SERVICENAME}-database
    networks:
      - traefik
      - ${SERVICENAME}
      - ldap

  moodle-adminer:
    image: adminer
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.${SERVICENAME}-adminer.entrypoints=websecure
      - traefik.http.routers.${SERVICENAME}-adminer.rule=Host(`${SERVICENAME}-adminer.${DOMAINNAME}`)
    networks:
      - traefik
      - ${SERVICENAME}
    depends_on:
      - ${SERVICENAME}-database

networks:
  traefik:
    name: traefik
    external: true
  ldap:
    name: ldap
    external: true
  moodle:
    name: ${SERVICENAME}
