version: '3.5'
services:
  moodle-database:
    image: mariadb
    restart: always
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD
    volumes:
      - "./docker/sql:/docker-entrypoint-initdb.d:ro"
      - "${VOLUMES_DIR}/mariadb:/var/lib/mysql"
    networks:
      - moodle

  moodle-adminer:
    image: adminer
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.moodle-adminer.entrypoints=websecure
      - traefik.http.routers.moodle-adminer.rule=Host(`moodle-adminer.${DOMAINNAME}`)
      - traefik.http.routers.moodle-adminer.tls=true
      - traefik.http.routers.moodle-adminer.tls.certresolver=myresolver
      - traefik.http.routers.moodle-adminer.middlewares=secheader
    networks:
      - traefik
      - moodle
    depends_on:
      - moodle-database

  moodle:
    build:
      context: .
    image: mindhochschulnetzwerk/moodle
    environment:
      - WWW_ROOT=https://www.${DOMAINNAME}
      - DB_HOST=moodle-database
      - DB_USER=user
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=database
      - SMTP_HOST
      - SMTP_SECURE
      - SMTP_AUTH_TYPE
      - SMTP_USER
      - SMTP_PASSWORD
      - IMAP_HOST
      - IMAP_SSL
      - IMAP_USER
      - IMAP_PASSWORD
      - LDAP_HOST=ldap://ldap:389/
      - LDAP_BIND_DN=cn=admin,dc=mind-hochschul-netzwerk,dc=de
      - LDAP_BIND_PASSWORD
    volumes:
      - "./docker/moodledata-init.tar.bz2:/moodledata-init.tar.bz2:ro"
      - "${VOLUMES_DIR}/moodledata:/moodledata"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.moodle.entrypoints=websecure
      - traefik.http.routers.moodle.rule=Host(`${DOMAINNAME}`) || Host(`moodle.${DOMAINNAME}`) || Host(`www.${DOMAINNAME}`) || Host(`www.moodle.${DOMAINNAME}`)
      - traefik.http.routers.moodle.tls=true
      - traefik.http.routers.moodle.tls.certresolver=myresolver
      - traefik.http.routers.moodle.middlewares=secheader
    depends_on:
      - moodle-database
    networks:
      - traefik
      - moodle
      - ldap

networks:
  traefik:
    name: traefik
    external: true
  ldap:
    name: ldap
    external: true
  moodle:
    name: moodle
